version: '3.1'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
      
    volumes:
      - ./script.sql:/script.sql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Script SQL pour l'initialisation
      - data:/var/lib/postgresql/data  # pour éviter de perdre les données lorsque le conteneur est arrêté

volumes:
  data:
